"""The run artifact: schema (SPEC §4), reader, writer, validator, and RunContext."""

from engine.artifact.context import Capability, RunContext
from engine.artifact.models import (
    DEFAULT_VIEWPORTS,
    SCHEMA_VERSION,
    VIEWPORT_PRESETS,
    AlignmentSet,
    Box,
    ColourUsage,
    ConsoleMessage,
    ElementRecord,
    ElementStyles,
    FontInfo,
    ImageInfo,
    LayoutRecord,
    LinkInfo,
    Metrics,
    NetworkEntry,
    NetworkSize,
    NetworkTiming,
    PageArtifact,
    PageRecord,
    RepeatedGroup,
    RunArtifact,
    RunConfig,
    RunManifest,
    RunStatus,
    SpacingBucket,
    TypeStyleUsage,
    Viewport,
)
from engine.artifact.store import RunPaths, read_run, validate, write_run

__all__ = [
    "DEFAULT_VIEWPORTS",
    "SCHEMA_VERSION",
    "VIEWPORT_PRESETS",
    "AlignmentSet",
    "Box",
    "Capability",
    "ColourUsage",
    "ConsoleMessage",
    "ElementRecord",
    "ElementStyles",
    "FontInfo",
    "ImageInfo",
    "LayoutRecord",
    "LinkInfo",
    "Metrics",
    "NetworkEntry",
    "NetworkSize",
    "NetworkTiming",
    "PageArtifact",
    "PageRecord",
    "RepeatedGroup",
    "RunArtifact",
    "RunConfig",
    "RunContext",
    "RunManifest",
    "RunPaths",
    "RunStatus",
    "SpacingBucket",
    "TypeStyleUsage",
    "Viewport",
    "read_run",
    "validate",
    "write_run",
]
